// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Dock {
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget Dock
        this.Name = "Dock";
        this.Title = Mono.Unix.Catalog.GetString("Settings");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.Resizable = false;
        this.AllowGrow = false;
        this.Decorated = false;
        this.SkipPagerHint = true;
        this.SkipTaskbarHint = true;
        this.FocusOnMap = false;
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 157;
        this.DefaultHeight = 129;
        this.Hide();
    }
}
