// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox8;
    
    private Gtk.VBox vbox9;
    
    private Gtk.HBox hbox11;
    
    private Gtk.Button button3;
    
    private Gtk.Button button4;
    
    private Gtk.Button button1;
    
    private Gtk.ComboBox combobox3;
    
    private Gtk.HBox hbox2;
    
    private Gtk.HSeparator hseparator1;
    
    private Gtk.HBox hbox5;
    
    private Gtk.Image image4;
    
    private Gtk.Label label3;
    
    private Gtk.HBox hbox12;
    
    private Gtk.Entry entry1;
    
    private Gtk.CheckButton checkbutton9;
    
    private Gtk.HSeparator hseparator2;
    
    private Gtk.HBox hbox6;
    
    private Gtk.Image image3;
    
    private Gtk.Label label4;
    
    private Gtk.HBox hbox13;
    
    private Gtk.Label label11;
    
    private Gtk.SpinButton spinbutton7;
    
    private Gtk.Label label10;
    
    private Gtk.SpinButton spinbutton6;
    
    private Gtk.Label label9;
    
    private Gtk.SpinButton spinbutton5;
    
    private Gtk.CheckButton checkbutton10;
    
    private Gtk.HBox hbox1;
    
    private Gtk.HSeparator hseparator3;
    
    private Gtk.HBox hbox14;
    
    private Gtk.VBox vbox10;
    
    private Gtk.CheckButton checkbutton11;
    
    private Gtk.CheckButton checkbutton15;
    
    private Gtk.VBox vbox11;
    
    private Gtk.CheckButton checkbutton12;
    
    private Gtk.CheckButton checkbutton16;
    
    private Gtk.VBox vbox12;
    
    private Gtk.CheckButton checkbutton13;
    
    private Gtk.CheckButton checkbutton17;
    
    private Gtk.VBox vbox13;
    
    private Gtk.CheckButton checkbutton18;
    
    private Gtk.HSeparator hseparator4;
    
    private Gtk.Image image2;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Label label2;
    
    private Gtk.HScale hscale2;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label label1;
    
    private Gtk.FileChooserButton filechooserbutton1;
    
    private Gtk.VBox vbox14;
    
    private Gtk.HBox hbox7;
    
    private Gtk.Image image1;
    
    private Gtk.Label label5;
    
    private Gtk.HBox hbox15;
    
    private Gtk.Label label12;
    
    private Gtk.FileChooserButton filechooserbutton2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Galarm");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox8 = new Gtk.VBox();
        this.vbox8.Name = "vbox8";
        this.vbox8.Spacing = 6;
        this.vbox8.BorderWidth = ((uint)(14));
        // Container child vbox8.Gtk.Box+BoxChild
        this.vbox9 = new Gtk.VBox();
        this.vbox9.Name = "vbox9";
        this.vbox9.Spacing = 6;
        // Container child vbox9.Gtk.Box+BoxChild
        this.hbox11 = new Gtk.HBox();
        this.hbox11.Name = "hbox11";
        this.hbox11.Spacing = 6;
        // Container child hbox11.Gtk.Box+BoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Create New");
        this.hbox11.Add(this.button3);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox11[this.button3]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox11.Gtk.Box+BoxChild
        this.button4 = new Gtk.Button();
        this.button4.CanFocus = true;
        this.button4.Name = "button4";
        this.button4.UseUnderline = true;
        this.button4.Label = Mono.Unix.Catalog.GetString("Discard");
        this.hbox11.Add(this.button4);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox11[this.button4]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        // Container child hbox11.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Delete");
        this.hbox11.Add(this.button1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox11[this.button1]));
        w3.PackType = ((Gtk.PackType)(1));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        // Container child hbox11.Gtk.Box+BoxChild
        this.combobox3 = Gtk.ComboBox.NewText();
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Select Alarm"));
        this.combobox3.Name = "combobox3";
        this.combobox3.Active = 0;
        this.hbox11.Add(this.combobox3);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox11[this.combobox3]));
        w4.PackType = ((Gtk.PackType)(1));
        w4.Position = 3;
        w4.Expand = false;
        w4.Fill = false;
        this.vbox9.Add(this.hbox11);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox9[this.hbox11]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child vbox9.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.hseparator1 = new Gtk.HSeparator();
        this.hseparator1.Name = "hseparator1";
        this.hbox2.Add(this.hseparator1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.hseparator1]));
        w6.Position = 0;
        this.vbox9.Add(this.hbox2);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox9[this.hbox2]));
        w7.Position = 1;
        w7.Expand = false;
        w7.Fill = false;
        w7.Padding = ((uint)(10));
        // Container child vbox9.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.image4 = new Gtk.Image();
        this.image4.Name = "image4";
        this.image4.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        this.hbox5.Add(this.image4);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox5[this.image4]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("<b>Name and activate your alarm</b>");
        this.label3.UseMarkup = true;
        this.hbox5.Add(this.label3);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox5[this.label3]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        this.vbox9.Add(this.hbox5);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox9[this.hbox5]));
        w10.Position = 2;
        w10.Expand = false;
        w10.Fill = false;
        // Container child vbox9.Gtk.Box+BoxChild
        this.hbox12 = new Gtk.HBox();
        this.hbox12.Name = "hbox12";
        this.hbox12.Spacing = 6;
        // Container child hbox12.Gtk.Box+BoxChild
        this.entry1 = new Gtk.Entry();
        this.entry1.CanFocus = true;
        this.entry1.Name = "entry1";
        this.entry1.Text = Mono.Unix.Catalog.GetString("My new alarm");
        this.entry1.IsEditable = true;
        this.entry1.MaxLength = 30;
        this.entry1.InvisibleChar = '●';
        this.hbox12.Add(this.entry1);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox12[this.entry1]));
        w11.Position = 0;
        // Container child hbox12.Gtk.Box+BoxChild
        this.checkbutton9 = new Gtk.CheckButton();
        this.checkbutton9.CanFocus = true;
        this.checkbutton9.Name = "checkbutton9";
        this.checkbutton9.Label = Mono.Unix.Catalog.GetString("Active");
        this.checkbutton9.DrawIndicator = true;
        this.checkbutton9.UseUnderline = true;
        this.hbox12.Add(this.checkbutton9);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox12[this.checkbutton9]));
        w12.PackType = ((Gtk.PackType)(1));
        w12.Position = 1;
        this.vbox9.Add(this.hbox12);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox9[this.hbox12]));
        w13.Position = 3;
        w13.Expand = false;
        w13.Fill = false;
        // Container child vbox9.Gtk.Box+BoxChild
        this.hseparator2 = new Gtk.HSeparator();
        this.hseparator2.Name = "hseparator2";
        this.vbox9.Add(this.hseparator2);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox9[this.hseparator2]));
        w14.Position = 4;
        w14.Expand = false;
        w14.Fill = false;
        w14.Padding = ((uint)(10));
        // Container child vbox9.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.image3 = new Gtk.Image();
        this.image3.Name = "image3";
        this.image3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_form-time-field", Gtk.IconSize.Menu, 16);
        this.hbox6.Add(this.image3);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox6[this.image3]));
        w15.Position = 0;
        w15.Expand = false;
        w15.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("<b>Alarm time settings</b>");
        this.label4.UseMarkup = true;
        this.hbox6.Add(this.label4);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox6[this.label4]));
        w16.Position = 1;
        w16.Expand = false;
        w16.Fill = false;
        this.vbox9.Add(this.hbox6);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox9[this.hbox6]));
        w17.Position = 5;
        w17.Expand = false;
        w17.Fill = false;
        // Container child vbox9.Gtk.Box+BoxChild
        this.hbox13 = new Gtk.HBox();
        this.hbox13.Name = "hbox13";
        this.hbox13.Spacing = 6;
        // Container child hbox13.Gtk.Box+BoxChild
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.LabelProp = Mono.Unix.Catalog.GetString("Hour");
        this.hbox13.Add(this.label11);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox13[this.label11]));
        w18.Position = 0;
        w18.Expand = false;
        w18.Fill = false;
        // Container child hbox13.Gtk.Box+BoxChild
        this.spinbutton7 = new Gtk.SpinButton(0, 23, 1);
        this.spinbutton7.CanFocus = true;
        this.spinbutton7.Name = "spinbutton7";
        this.spinbutton7.Adjustment.PageIncrement = 10;
        this.spinbutton7.ClimbRate = 1;
        this.spinbutton7.Numeric = true;
        this.hbox13.Add(this.spinbutton7);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox13[this.spinbutton7]));
        w19.Position = 1;
        w19.Expand = false;
        w19.Fill = false;
        // Container child hbox13.Gtk.Box+BoxChild
        this.label10 = new Gtk.Label();
        this.label10.Name = "label10";
        this.label10.LabelProp = Mono.Unix.Catalog.GetString("Minute");
        this.hbox13.Add(this.label10);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox13[this.label10]));
        w20.Position = 2;
        w20.Expand = false;
        w20.Fill = false;
        // Container child hbox13.Gtk.Box+BoxChild
        this.spinbutton6 = new Gtk.SpinButton(0, 59, 1);
        this.spinbutton6.CanFocus = true;
        this.spinbutton6.Name = "spinbutton6";
        this.spinbutton6.Adjustment.PageIncrement = 10;
        this.spinbutton6.ClimbRate = 1;
        this.spinbutton6.Numeric = true;
        this.hbox13.Add(this.spinbutton6);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox13[this.spinbutton6]));
        w21.Position = 3;
        w21.Expand = false;
        w21.Fill = false;
        // Container child hbox13.Gtk.Box+BoxChild
        this.label9 = new Gtk.Label();
        this.label9.Name = "label9";
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("Second");
        this.hbox13.Add(this.label9);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox13[this.label9]));
        w22.Position = 4;
        w22.Expand = false;
        w22.Fill = false;
        // Container child hbox13.Gtk.Box+BoxChild
        this.spinbutton5 = new Gtk.SpinButton(0, 59, 1);
        this.spinbutton5.CanFocus = true;
        this.spinbutton5.Name = "spinbutton5";
        this.spinbutton5.Adjustment.PageIncrement = 10;
        this.spinbutton5.ClimbRate = 1;
        this.spinbutton5.Numeric = true;
        this.hbox13.Add(this.spinbutton5);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox13[this.spinbutton5]));
        w23.Position = 5;
        w23.Expand = false;
        w23.Fill = false;
        // Container child hbox13.Gtk.Box+BoxChild
        this.checkbutton10 = new Gtk.CheckButton();
        this.checkbutton10.CanFocus = true;
        this.checkbutton10.Name = "checkbutton10";
        this.checkbutton10.Label = Mono.Unix.Catalog.GetString("Every Day");
        this.checkbutton10.Active = true;
        this.checkbutton10.DrawIndicator = true;
        this.checkbutton10.UseUnderline = true;
        this.hbox13.Add(this.checkbutton10);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox13[this.checkbutton10]));
        w24.Position = 6;
        this.vbox9.Add(this.hbox13);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox9[this.hbox13]));
        w25.Position = 6;
        w25.Expand = false;
        w25.Fill = false;
        this.vbox8.Add(this.vbox9);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
        w26.Position = 0;
        w26.Expand = false;
        w26.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.hseparator3 = new Gtk.HSeparator();
        this.hseparator3.Name = "hseparator3";
        this.hbox1.Add(this.hseparator3);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox1[this.hseparator3]));
        w27.Position = 0;
        this.vbox8.Add(this.hbox1);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox8[this.hbox1]));
        w28.Position = 1;
        w28.Expand = false;
        w28.Fill = false;
        w28.Padding = ((uint)(10));
        // Container child vbox8.Gtk.Box+BoxChild
        this.hbox14 = new Gtk.HBox();
        this.hbox14.Name = "hbox14";
        this.hbox14.Spacing = 6;
        // Container child hbox14.Gtk.Box+BoxChild
        this.vbox10 = new Gtk.VBox();
        this.vbox10.Name = "vbox10";
        this.vbox10.Spacing = 6;
        // Container child vbox10.Gtk.Box+BoxChild
        this.checkbutton11 = new Gtk.CheckButton();
        this.checkbutton11.CanFocus = true;
        this.checkbutton11.Name = "checkbutton11";
        this.checkbutton11.Label = Mono.Unix.Catalog.GetString("Mon");
        this.checkbutton11.DrawIndicator = true;
        this.checkbutton11.UseUnderline = true;
        this.vbox10.Add(this.checkbutton11);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox10[this.checkbutton11]));
        w29.Position = 0;
        w29.Expand = false;
        w29.Fill = false;
        // Container child vbox10.Gtk.Box+BoxChild
        this.checkbutton15 = new Gtk.CheckButton();
        this.checkbutton15.CanFocus = true;
        this.checkbutton15.Name = "checkbutton15";
        this.checkbutton15.Label = Mono.Unix.Catalog.GetString("Fri");
        this.checkbutton15.DrawIndicator = true;
        this.checkbutton15.UseUnderline = true;
        this.vbox10.Add(this.checkbutton15);
        Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.vbox10[this.checkbutton15]));
        w30.Position = 1;
        w30.Expand = false;
        w30.Fill = false;
        this.hbox14.Add(this.vbox10);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.hbox14[this.vbox10]));
        w31.Position = 0;
        // Container child hbox14.Gtk.Box+BoxChild
        this.vbox11 = new Gtk.VBox();
        this.vbox11.Name = "vbox11";
        this.vbox11.Spacing = 6;
        // Container child vbox11.Gtk.Box+BoxChild
        this.checkbutton12 = new Gtk.CheckButton();
        this.checkbutton12.CanFocus = true;
        this.checkbutton12.Name = "checkbutton12";
        this.checkbutton12.Label = Mono.Unix.Catalog.GetString("Tues");
        this.checkbutton12.DrawIndicator = true;
        this.checkbutton12.UseUnderline = true;
        this.vbox11.Add(this.checkbutton12);
        Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.vbox11[this.checkbutton12]));
        w32.Position = 0;
        w32.Expand = false;
        w32.Fill = false;
        // Container child vbox11.Gtk.Box+BoxChild
        this.checkbutton16 = new Gtk.CheckButton();
        this.checkbutton16.CanFocus = true;
        this.checkbutton16.Name = "checkbutton16";
        this.checkbutton16.Label = Mono.Unix.Catalog.GetString("Sat");
        this.checkbutton16.DrawIndicator = true;
        this.checkbutton16.UseUnderline = true;
        this.vbox11.Add(this.checkbutton16);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.vbox11[this.checkbutton16]));
        w33.Position = 1;
        w33.Expand = false;
        w33.Fill = false;
        this.hbox14.Add(this.vbox11);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox14[this.vbox11]));
        w34.Position = 1;
        // Container child hbox14.Gtk.Box+BoxChild
        this.vbox12 = new Gtk.VBox();
        this.vbox12.Name = "vbox12";
        this.vbox12.Spacing = 6;
        // Container child vbox12.Gtk.Box+BoxChild
        this.checkbutton13 = new Gtk.CheckButton();
        this.checkbutton13.CanFocus = true;
        this.checkbutton13.Name = "checkbutton13";
        this.checkbutton13.Label = Mono.Unix.Catalog.GetString("Wed");
        this.checkbutton13.DrawIndicator = true;
        this.checkbutton13.UseUnderline = true;
        this.vbox12.Add(this.checkbutton13);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox12[this.checkbutton13]));
        w35.Position = 0;
        w35.Expand = false;
        w35.Fill = false;
        // Container child vbox12.Gtk.Box+BoxChild
        this.checkbutton17 = new Gtk.CheckButton();
        this.checkbutton17.CanFocus = true;
        this.checkbutton17.Name = "checkbutton17";
        this.checkbutton17.Label = Mono.Unix.Catalog.GetString("Sun");
        this.checkbutton17.DrawIndicator = true;
        this.checkbutton17.UseUnderline = true;
        this.vbox12.Add(this.checkbutton17);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox12[this.checkbutton17]));
        w36.Position = 1;
        w36.Expand = false;
        w36.Fill = false;
        this.hbox14.Add(this.vbox12);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.hbox14[this.vbox12]));
        w37.Position = 2;
        // Container child hbox14.Gtk.Box+BoxChild
        this.vbox13 = new Gtk.VBox();
        this.vbox13.Name = "vbox13";
        this.vbox13.Spacing = 6;
        // Container child vbox13.Gtk.Box+BoxChild
        this.checkbutton18 = new Gtk.CheckButton();
        this.checkbutton18.CanFocus = true;
        this.checkbutton18.Name = "checkbutton18";
        this.checkbutton18.Label = Mono.Unix.Catalog.GetString("Thur");
        this.checkbutton18.DrawIndicator = true;
        this.checkbutton18.UseUnderline = true;
        this.vbox13.Add(this.checkbutton18);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.vbox13[this.checkbutton18]));
        w38.Position = 0;
        w38.Expand = false;
        w38.Fill = false;
        this.hbox14.Add(this.vbox13);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.hbox14[this.vbox13]));
        w39.Position = 3;
        this.vbox8.Add(this.hbox14);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox8[this.hbox14]));
        w40.Position = 2;
        w40.Expand = false;
        w40.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.hseparator4 = new Gtk.HSeparator();
        this.hseparator4.Name = "hseparator4";
        this.vbox8.Add(this.hseparator4);
        Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.vbox8[this.hseparator4]));
        w41.Position = 3;
        w41.Expand = false;
        w41.Fill = false;
        w41.Padding = ((uint)(10));
        // Container child vbox8.Gtk.Box+BoxChild
        this.image2 = new Gtk.Image();
        this.image2.Name = "image2";
        this.vbox8.Add(this.image2);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.vbox8[this.image2]));
        w42.PackType = ((Gtk.PackType)(1));
        w42.Position = 4;
        w42.Expand = false;
        w42.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Initial Volume");
        this.hbox4.Add(this.label2);
        Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.hbox4[this.label2]));
        w43.Position = 0;
        w43.Expand = false;
        w43.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.hscale2 = new Gtk.HScale(null);
        this.hscale2.CanFocus = true;
        this.hscale2.Name = "hscale2";
        this.hscale2.Adjustment.Lower = 1;
        this.hscale2.Adjustment.Upper = 100;
        this.hscale2.Adjustment.PageIncrement = 10;
        this.hscale2.Adjustment.StepIncrement = 1;
        this.hscale2.Adjustment.Value = 52;
        this.hscale2.DrawValue = true;
        this.hscale2.Digits = 0;
        this.hscale2.ValuePos = ((Gtk.PositionType)(2));
        this.hbox4.Add(this.hscale2);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox4[this.hscale2]));
        w44.PackType = ((Gtk.PackType)(1));
        w44.Position = 1;
        w44.Padding = ((uint)(10));
        this.vbox8.Add(this.hbox4);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.vbox8[this.hbox4]));
        w45.PackType = ((Gtk.PackType)(1));
        w45.Position = 5;
        w45.Expand = false;
        w45.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("PlayList / Audio File");
        this.hbox3.Add(this.label1);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.hbox3[this.label1]));
        w46.Position = 0;
        w46.Expand = false;
        w46.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.filechooserbutton1 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A Playlist or Audio File"), ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton1.Name = "filechooserbutton1";
        this.hbox3.Add(this.filechooserbutton1);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.hbox3[this.filechooserbutton1]));
        w47.Position = 1;
        w47.Padding = ((uint)(10));
        this.vbox8.Add(this.hbox3);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.vbox8[this.hbox3]));
        w48.PackType = ((Gtk.PackType)(1));
        w48.Position = 6;
        w48.Expand = false;
        w48.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.vbox14 = new Gtk.VBox();
        this.vbox14.Name = "vbox14";
        this.vbox14.Spacing = 6;
        // Container child vbox14.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.image1 = new Gtk.Image();
        this.image1.Name = "image1";
        this.image1.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_media-play", Gtk.IconSize.Menu, 16);
        this.hbox7.Add(this.image1);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.hbox7[this.image1]));
        w49.Position = 0;
        w49.Expand = false;
        w49.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("<b>Select your favourite player and audio file / playlist</b>");
        this.label5.UseMarkup = true;
        this.hbox7.Add(this.label5);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.hbox7[this.label5]));
        w50.Position = 1;
        w50.Expand = false;
        w50.Fill = false;
        this.vbox14.Add(this.hbox7);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.vbox14[this.hbox7]));
        w51.Position = 0;
        w51.Expand = false;
        w51.Fill = false;
        // Container child vbox14.Gtk.Box+BoxChild
        this.hbox15 = new Gtk.HBox();
        this.hbox15.Name = "hbox15";
        this.hbox15.Spacing = 6;
        // Container child hbox15.Gtk.Box+BoxChild
        this.label12 = new Gtk.Label();
        this.label12.Name = "label12";
        this.label12.LabelProp = Mono.Unix.Catalog.GetString("Player");
        this.hbox15.Add(this.label12);
        Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.hbox15[this.label12]));
        w52.Position = 0;
        w52.Expand = false;
        w52.Fill = false;
        // Container child hbox15.Gtk.Box+BoxChild
        this.filechooserbutton2 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton2.Name = "filechooserbutton2";
        this.hbox15.Add(this.filechooserbutton2);
        Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.hbox15[this.filechooserbutton2]));
        w53.PackType = ((Gtk.PackType)(1));
        w53.Position = 1;
        w53.Padding = ((uint)(10));
        this.vbox14.Add(this.hbox15);
        Gtk.Box.BoxChild w54 = ((Gtk.Box.BoxChild)(this.vbox14[this.hbox15]));
        w54.Position = 1;
        w54.Expand = false;
        w54.Fill = false;
        this.vbox8.Add(this.vbox14);
        Gtk.Box.BoxChild w55 = ((Gtk.Box.BoxChild)(this.vbox8[this.vbox14]));
        w55.PackType = ((Gtk.PackType)(1));
        w55.Position = 7;
        w55.Expand = false;
        w55.Fill = false;
        this.Add(this.vbox8);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 430;
        this.DefaultHeight = 630;
        this.button4.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
        this.button4.Clicked += new System.EventHandler(this.OnButton4Clicked);
        this.combobox3.Changed += new System.EventHandler(this.OnCombobox3Changed);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.checkbutton10.Clicked += new System.EventHandler(this.OnCheckbutton10Clicked);
        this.hscale2.ValueChanged += new System.EventHandler(this.OnHscale2ValueChanged);
    }
}
